version: "3"

services:
  postgres:
    image: postgres:latest
    restart: always

    ports:
      - 1234:5432

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080